# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CYPRESS_CACHE_FOLDER: cypress/cache

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    - name: Cache Cypress binary
      id: cache-cypress-binary
      uses: actions/cache@v2
      with:
        path: cypress/cache
        key: cypress-binary-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: |
        steps.cache-node-modules.outputs.cache-hit != 'true' ||
        steps.cache-cypress-binary.outputs.cache-hit != 'true'
      run: npm ci
    - name: Lint code
      run: npm run lint
    - name: Build SwaggerEditor
      run: npm run build
    - name: Run all tests
      run: npm test
      env:
        CI: true
    - name:  Test build artifacts
      run: npm run test:artifact
